service: serverless-flask # lambda name

package:
  patterns:
    - "!__pycache__/**"
    - "!.env"

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.app # entry point
    packRequirements: false
  pythonRequirements:
    dockerizeZip: non-linux

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-northeast-2
  lambdaHashingVersion: 20201221

functions:
  app:
    handler: wsgi_handler.handler # event -> webserver interface by wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY /ipo'